services:
  nginx:
      build: ./nginx
      ports:
          - "80:80"
          - "443:443"
      volumes:
          # Build of UI for controlling Robi
          - ./cancer_app_frontend/dist:/dist
      depends_on:
          - "python"

  python:
      build:
          context: ./python
      volumes:
          - ./python/backend:/backend
